version: '3.8'

services:
  db:
    image: postgres:13
    container_name: moovy-postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: moovy-backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: